sudo: false
language: php
php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm
services: sqlite3
before_script:
    - composer self-update
script:
    - composer install --prefer-source
    - php -r "copy('.env.example', '.env');"
    - chmod -R 777 tests/build
    - ./vendor/bin/phpunit
after_script:
    - php vendor/bin/coveralls -v
    - wget https://scrutinizer-ci.com/ocular.phar
    - if [[ ${TRAVIS_PHP_VERSION:0:3} == "5.5" ]]; then php ocular.phar code-coverage:upload --format=php-clover tests/build/clover.xml; fi
